name: Run Jobs.cz Scraper

# This workflow only runs the scraper and updates Google Docs.
# It does not commit or push any changes to the repository.

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 AM UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # Explicitly disable git operations
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: python scraper.py