name: Run Jobs.cz Scraper

# This workflow only runs the scraper and updates Google Docs.
# It does not commit or push any changes to the repository.

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 AM UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false  # Explicitly disable git operations
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo 'GOOGLE_SERVICE_ACCOUNT='"'"${{ secrets.GOOGLE_SERVICE_ACCOUNT }}"'"'' > .env
        echo "GOOGLE_DOC_ID=${{ secrets.GOOGLE_DOC_ID }}" >> .env
        
    - name: Run scraper
      run: python scraper.py
      
    - name: Check for scraper output
      if: always()
      run: |
        if [ -f "error.log" ]; then
          if grep -i "error" error.log > /dev/null; then
            echo "::error::Scraper encountered errors. Check error.log for details."
            grep -i "error" error.log
            exit 1
          else
            echo "Log file exists but contains no errors"
          fi
        fi 